options:
  kubeflow-trainer-image:
    default: docker.io/charmedkubeflow/kubeflow-trainer:2.1.0-5c8ae13-20260901041633
    description: |
      Container image to be used by the Kubeflow Trainer workload.
    type: string
  jobset-image:
    default: docker.io/charmedkubeflow/jobset:0.10.1-5c8ae13-20260901041638
    description: |
      Container image to be used by the JobSet workload.
    type: string
  lws-image:
    default: charmedkubeflow/lws:0.7.0-363849d-20260917083947
    description: |
      Container image to be used by the Leader Worker Set workload.
    type: string
