options:
  kubeflow-trainer-image:
    default: docker.io/charmedkubeflow/kubeflow-trainer:2.0.1-26331db-20260901041624
    description: |
      Container image to be used by the Kubeflow Trainer workload.
    type: string
  jobset-image:
    default: docker.io/charmedkubeflow/jobset:0.8.2-c6af5cc
    description: |
      Container image to be used by the JobSet workload.
    type: string
<<<<<<< HEAD
=======
  lws-image:
    default: charmedkubeflow/lws:0.7.0-363849d-20260917083947
    description: |
      Container image to be used by the Leader Worker Set workload.
    type: string
>>>>>>> 5a87afa (chore: Integrate latest lws rock (#52))
